# https://yazi-rs.github.io/docs/configuration/yazi#mgr
# hide the left panel (parent) because its just confusing to me
[mgr]
ratio = [0,5,4]

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]
